-- MySQL Script generated by MySQL Workbench
-- 12/01/21 23:15:40
-- Model: DAW2-ComparaPrecios    Version: 1.0

-- Proyecto en Grupo - Comparador de Precios de Productos, Comentarios y Valoraciones.
-- Desarrollo de Aplicaciones Web II.
-- Escuela Politécnica Superior de Zamora.
-- Universidad de Salamanca.
-- 

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema daw2_20_comparaprecios
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `daw2_20_comparaprecios` ;

-- -----------------------------------------------------
-- Schema daw2_20_comparaprecios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daw2_20_comparaprecios` DEFAULT CHARACTER SET utf8 ;
USE `daw2_20_comparaprecios` ;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`tiendas` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`tiendas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `nombre_tienda` TEXT NOT NULL COMMENT 'Nombre o denominación para la tienda.',
  `descripcion_tienda` TEXT NULL DEFAULT NULL COMMENT 'Descripción breve de la tienda o NULL si no es necesaria.',
  `lugar_tienda` TEXT NULL DEFAULT NULL COMMENT 'Descripción adicional del lugar donde esta la tienda o NULL si no se conoce, aunque no debería estar vacío este dato.',
  `url_tienda` TEXT NULL DEFAULT NULL COMMENT 'Dirección web externa (opcional) que enlaza con la página \"oficial\" de la tienda o NULL si no hay o no se conoce.',
  
  `direccion_tienda` TEXT NULL DEFAULT NULL COMMENT 'Direccion de la entidad o NULL si no quiere informar o no se conoce.',
  `region_id_tienda` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Región de localización de la tienda o CERO (como si fuera NULL) si no se sabe, o aún no está indicada, aunque es recomendable.',
  `telefono_tienda` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Telefono de la tienda o NULL si no se sabe o no hay.',
  
  `clasificacion_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Clasificación de la tienda o CERO si no existe o aún no está indicada (como si fuera NULL).',
  -- Etiquetas -- Se relacionan en tabla aparte.
  `imagen_id` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Nombre identificativo (fichero interno) con la imagen principal o \"de presentación\" de la tienda, o NULL si no hay.',
  
  `sumaValores` INT(9) NOT NULL DEFAULT '0' COMMENT 'Suma acumulada de las valoraciones para la tienda.',
  `totalVotos` INT(9) NOT NULL DEFAULT '0' COMMENT 'Contador de votos (valoraciones) emitidas para la tienda.',
  
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de tienda visible a los usuarios o invisible (se está manteniendo o está desactivada por otras causas): 0=Invisible, 1=Visible.',
  `cerrada` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de tienda cancelada, eliminada o suspendida: 0=No (activa), 1=Eliminada por solicitud de baja, 2=Suspendida, 3=Cancelada por Inadecuada, ...',
  
  `num_denuncias` INT(9) NOT NULL DEFAULT '0' COMMENT 'Contador de denuncias de la tienda o CERO si no ha tenido.',
  `fecha_denuncia1` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la primera denuncia. Debería estar a NULL si no tiene denuncias (contador a cero), o si el contador se reinicia.',
  `notas_denuncia` TEXT NULL DEFAULT NULL COMMENT 'Notas o texto visible con el motivo de la primera denuncia de la tienda o NULL si no hay -se muestra este campo según el estado de \"bloqueada\"-.',
  
  `bloqueada` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de tienda bloqueada: 0=No, 1=Si(bloqueada por denuncias), 2=Si(bloqueada por moderador o administrador), ...',
  `fecha_bloqueo` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora del bloqueo de la tienda. Debería estar a NULL si no está bloqueada o si se desbloquea.',
  `notas_bloqueo` TEXT NULL DEFAULT NULL COMMENT 'Notas visibles sobre el motivo del bloqueo de la tienda o NULL si no hay -se muestra por defecto según indique \"bloqueada\"-.',
  
  -- Comentarios -- Se relacionan en tabla aparte.
  `cerrado_comentar` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de tienda cerrada para agregar comentarios: 0=No, 1=Si.',
  
  -- Usuario relacionado --
  `usuario_id` INT(12) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Usuario relacionado con estos datos principales, propietario de la tienda o CERO (como si fuera NULL) si no tiene usuario vinculado o no se conoce, no existe, o aún no está indicado.',
  
  -- INI: Entidad(Empresa o Persona) --
  `nif_cif` VARCHAR(12) NOT NULL COMMENT 'Identificador de la entidad.',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre si la entidad es de tipo persona.',
  `apellidos` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Apellidos si la entidad es de tipo persona.',
  `razon_social` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Razon social de la entidad si es de tipo empresa, o NULL si con el \"nombre y apellidos\" como persona es suficiente.',
  `direccion` TEXT NULL DEFAULT NULL COMMENT 'Direccion de la entidad o NULL si no quiere informar o no se conoce.',
  `region_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Región de localización de la entidad o CERO si no lo quiere informar (como si fuera NULL), aunque es recomendable.',
  `telefono_contacto` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Telefono de contacto directo con la entidad o NULL si no se sabe o no hay.',
  -- FIN: Entidad --
  
  -- INI: Registro de Usuario --
  `crea_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha creado el registro o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `crea_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de creación del registro o NULL si no se conoce por algún motivo.',
  `modi_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha modificado el registro por última vez o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `modi_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la última modificación del registro o NULL si no se conoce por algún motivo.',
  `notas_admin` TEXT NULL DEFAULT NULL COMMENT 'Notas adicionales que solo ven/modifican los moderadores/administradores sobre los datos del regsitro o NULL si no hay.',
  -- FIN: Registro de Usuario --
  
  -- Artículos-Tienda -- Se relacionan en tabla aparte.
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`articulos` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`articulos` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `nombre` TEXT NOT NULL COMMENT 'Nombre o denominación para el artículo.',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Descripción breve del artículo o NULL si no es necesaria.',
  
  `categoria_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Categoria de clasificación del artículo o CERO si no existe o aún no está indicada (como si fuera NULL).',
  -- Etiquetas -- Se relacionan en tabla aparte.
  `imagen_id` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Nombre identificativo (fichero interno) con la imagen principal o \"de presentación\" del artículo, o NULL si no hay.',
  
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo visible a los usuarios o invisible (se está manteniendo o está desactivado por otras causas): 0=Invisible, 1=Visible.',
  `cerrado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo cancelado, eliminado o suspendido: 0=No (activo), 1=Eliminado por solicitud de baja, 2=Suspendido, 3=Cancelado por Inadecuado, ...',
  `comun` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo común a cualquier tienda que lo relacione o particular de una tienda, creado o marcado así por un moderador/administrador: 0=Particular, 1=Comun. Habrá un proceso que pueda convertir un artículo particular en común.',
  
  -- Artículos-Tienda -- Se relacionan en tabla aparte.
  
  -- INI: Registro de Usuario --
  `crea_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha creado el registro o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `crea_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de creación del registro o NULL si no se conoce por algún motivo.',
  `modi_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha modificado el registro por última vez o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `modi_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la última modificación del registro o NULL si no se conoce por algún motivo.',
  `notas_admin` TEXT NULL DEFAULT NULL COMMENT 'Notas adicionales que solo ven/modifican los moderadores/administradores sobre los datos del regsitro o NULL si no hay.',
  -- FIN: Registro de Usuario --
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`articulos_tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`articulos_tienda` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`articulos_tienda` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `articulo_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Artículo relacionado o CERO (como si fuera NULL) si no existe o aún no está indicado, aunque no debería ser así.',
  `tienda_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Tienda a la que pertenece el artículo relacionado o CERO (como si fuera NULL) si no existe o aún no está indicada, aunque no debería ser así.',
  `imagen_id` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Nombre identificativo (fichero interno) con la imagen opcional del artículo, o NULL si no hay, mostrándose en este caso la imagen principal que pueda tener el artículo.',
  `url_articulo` TEXT NULL DEFAULT NULL COMMENT 'Dirección web externa (opcional) que enlaza con la página \"oficial\" de la tienda+artículo o NULL si no hay o no se conoce.',
  
  `precio` FLOAT NOT NULL DEFAULT '0' COMMENT 'Precio actual del artículo en la tienda.',
  -- Historico-Precios -- Se relacionan en tabla aparte.
  -- Ofertas -- Se relacionan en tabla aparte.
  
  `sumaValores` INT(9) NOT NULL DEFAULT '0' COMMENT 'Suma acumulada de las valoraciones para el artículo en la tienda.',
  `totalVotos` INT(9) NOT NULL DEFAULT '0' COMMENT 'Contador de votos (valoraciones) emitidas para el artículo en la tienda.',
  
  `visible` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo visible a los usuarios o invisible (se está manteniendo o está desactivado por otras causas): 0=Invisible, 1=Visible.',
  `cerrado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo cancelado, eliminado o suspendido: 0=No (activo), 1=Eliminado por solicitud de baja, 2=Suspendido, 3=Cancelado por Inadecuado, ...',
  
  `num_denuncias` INT(9) NOT NULL DEFAULT '0' COMMENT 'Contador de denuncias del artículo en la tienda o CERO si no ha tenido.',
  `fecha_denuncia1` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la primera denuncia. Debería estar a NULL si no tiene denuncias (contador a cero), o si el contador se reinicia.',
  `notas_denuncia` TEXT NULL DEFAULT NULL COMMENT 'Notas o texto visible con el motivo de la primera denuncia del artículo o NULL si no hay -se muestra este campo según el estado de \"bloqueado\"-.',
  
  `bloqueado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo bloqueado: 0=No, 1=Si(bloqueado por denuncias), 2=Si(bloqueado por moderador o administrador), ...',
  `fecha_bloqueo` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora del bloqueo del artículo. Debería estar a NULL si no está bloqueado o si se desbloquea.',
  `notas_bloqueo` TEXT NULL DEFAULT NULL COMMENT 'Notas visibles sobre el motivo del bloqueo del artículo o NULL si no hay -se muestra por defecto según indique \"bloqueado\"-.',
  
  -- Comentarios -- Se relacionan en tabla aparte.
  `cerrado_comentar` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de artículo cerrado para agregar comentarios: 0=No, 1=Si.',
  
  -- INI: Registro de Usuario --
  `crea_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha creado el registro o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `crea_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de creación del registro o NULL si no se conoce por algún motivo.',
  `modi_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha modificado el registro por última vez o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `modi_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la última modificación del registro o NULL si no se conoce por algún motivo.',
  `notas_admin` TEXT NULL DEFAULT NULL COMMENT 'Notas adicionales que solo ven/modifican los moderadores/administradores sobre los datos del regsitro o NULL si no hay.',
  -- FIN: Registro de Usuario --
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`clasificadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`clasificadores` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`clasificadores` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `nombre` VARCHAR(25) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Texto adicional que describe el clasificador o NULL si no es necesario.',
  `icono` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Nombre del icono relacionado de entre los disponibles en la aplicación (carpeta iconos posibles).',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`categorias` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`categorias` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `nombre` VARCHAR(25) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Texto adicional que describe la categoria.',
  `icono` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Nombre del icono relacionado de entre los disponibles en la aplicación (carpeta iconos posibles).',
  `categoria_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Categoria relacionada, para poder realizar la jerarquía de categorías. Nodo padre de la jerarquía de categoría, o CERO si es nodo raiz (como si fuera NULL).',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`etiquetas` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`etiquetas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `nombre` VARCHAR(25) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL COMMENT 'Texto adicional que describe la etiqueta o NULL si no es necesario.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`tiendas_etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`tiendas_etiquetas` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`tiendas_etiquetas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `tienda_id` INT(12) UNSIGNED NOT NULL COMMENT 'Tienda relacionada.',
  `etiqueta_id` INT(12) UNSIGNED NOT NULL COMMENT 'Etiqueta relacionada.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`articulos_etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`articulos_etiquetas` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`articulos_etiquetas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `articulo_id` INT(12) UNSIGNED NOT NULL COMMENT 'Artículo relacionado.',
  `etiqueta_id` INT(12) UNSIGNED NOT NULL COMMENT 'Etiqueta relacionada.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`regiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`regiones` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`regiones` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `clase_region` CHAR(1) NOT NULL COMMENT 'Código de clase de la región (fijado desde programación): C=Continente, P=Pais, E=Estado, P=Provincia, ...',
  `nombre` VARCHAR(50) NOT NULL COMMENT 'Nombre de la zona que la identifica.',
  `region_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Región relacionada. Nodo padre de la jerarquia o CERO si es nodo raiz.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`historico_precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`historico_precios` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`historico_precios` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `articulo_id` INT(12) UNSIGNED NOT NULL COMMENT 'Artículo relacionado.',
  `tienda_id` INT(12) UNSIGNED NOT NULL COMMENT 'Tienda relacionada.',
  
  `fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de captura del precio del artículo en la tienda.',
  `precio` FLOAT NOT NULL DEFAULT '0' COMMENT 'Precio capturado en la fecha/hora indicada.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`ofertas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`ofertas` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`ofertas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `articulo_id` INT(12) UNSIGNED NOT NULL COMMENT 'Artículo relacionado.',
  `tienda_id` INT(12) UNSIGNED NOT NULL COMMENT 'Tienda relacionada.',
  `texto` TEXT NOT NULL COMMENT 'El texto o descripción de la oferta.',
  `fecha_desde` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de inicio de la oferta o NULL si no se conoce (mostrar como *próximamente* en función de la fecha de creación del registro).',
  `fecha_hasta` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de finalización de la oferta o NULL si no se conoce (no caduca automáticamente).',
  `precio_oferta` FLOAT NOT NULL DEFAULT '0' COMMENT 'Precio del artículo durante el intervalo de tiempo de la oferta.',
  `precio_original` FLOAT NOT NULL DEFAULT '0' COMMENT 'Precio del artículo copiado antes de comenzar el intervalo de tiempo de la oferta.',
  
  -- INI: Registro de Usuario --
  `crea_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha creado el registro o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `crea_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de creación del registro o NULL si no se conoce por algún motivo.',
  `modi_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha modificado el registro por última vez o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `modi_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la última modificación del registro o NULL si no se conoce por algún motivo.',
  `notas_admin` TEXT NULL DEFAULT NULL COMMENT 'Notas adicionales que solo ven/modifican los moderadores/administradores sobre los datos del regsitro o NULL si no hay.',
  -- FIN: Registro de Usuario --  
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`comentarios` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `tienda_id` INT(12) UNSIGNED NOT NULL COMMENT 'Tienda relacionada con el comentario, siempre habrá alguna.',
  `articulo_id` INT(12) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Artículo relacionado con el comentario o CERO si el comentario es sólo de tienda.',
  
  `valoracion` INT(2) NOT NULL DEFAULT '0' COMMENT 'Valoración dada a la tienda o al artículo en el comentario. El valor mínimo y máximo se pueden fijar por programación o configurado en la aplicación.',
  `texto` TEXT NOT NULL COMMENT 'El texto del comentario. Poner un límite por programación o configurado en la aplicación.',
  
  `comentario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Comentario relacionado, si se permiten encadenar respuestas. Nodo padre de la jerarquia de comentarios o CERO si es nodo raiz.',
  `cerrado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de cierre de respuestas al comentario: 0=No, 1=Si(No se puede responder al comentario)',
  
  `num_denuncias` INT(9) NOT NULL DEFAULT '0' COMMENT 'Contador de denuncias del comentario o CERO si no ha tenido.',
  `fecha_denuncia1` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la primera denuncia. Debería estar a NULL si no tiene denuncias (contador a cero), o si el contador se reinicia.',
  `notas_denuncia` TEXT NULL DEFAULT NULL COMMENT 'Notas o texto visible con el motivo de la primera denuncia del comentario o NULL si no hay -se muestra este campo según el estado de \"bloqueado\"-.',
  
  `bloqueado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de comentario bloqueado: 0=No, 1=Si(bloqueado por denuncias), 2=Si(bloqueado por administrador), ...',
  `fecha_bloqueo` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora del bloqueo del comentario. Debería estar a NULL si no está bloqueado o si se desbloquea.',
  `notas_bloqueo` TEXT NULL DEFAULT NULL COMMENT 'Notas visibles sobre el motivo del bloqueo del comentario o NULL si no hay -se muestra por defecto según indique \"bloqueado\"-.',
  
  -- INI: Registro de Usuario --
  `crea_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha creado el registro o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `crea_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de creación del registro o NULL si no se conoce por algún motivo.',
  `modi_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario que ha modificado el registro por última vez o CERO (como si fuera NULL) si no existe o se hizo por un administrador de sistema.',
  `modi_fecha` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de la última modificación del registro o NULL si no se conoce por algún motivo.',
  `notas_admin` TEXT NULL DEFAULT NULL COMMENT 'Notas adicionales que solo ven/modifican los moderadores/administradores sobre los datos del regsitro o NULL si no hay.',
  -- FIN: Registro de Usuario --  
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`seguimientos_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`seguimientos_usuario` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`seguimientos_usuario` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `usuario_id` INT(12) UNSIGNED NOT NULL COMMENT 'Usuario relacionado, seguidor de la tienda, o el artículo o la oferta indicada. Al menos uno de los IDs no debe ser CERO.',
  
  `tienda_id` INT(12) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Tienda relacionada con el seguimiento, o CERO si no se sigue a una tienda.',  
  `articulo_id` INT(12) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Artículo relacionado con el seguimiento o CERO si no se sigue a un artículo.',
  `oferta_id` INT(12) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Oferta relacionada con el seguimiento o CERO si no se sigue a una oferta.',
  
  `fecha_alta` DATETIME NOT NULL COMMENT 'Fecha y Hora de activación del seguimiento por parte del usuario.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`avisos_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`avisos_usuarios` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`avisos_usuarios` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `fecha_aviso` DATETIME NOT NULL COMMENT 'Fecha y Hora de creación del aviso.',
  `clase_aviso` CHAR(1) NOT NULL DEFAULT 'M' COMMENT 'Código de clase de aviso (fijado desde programación): A=Aviso, N=Notificación, D=Denuncia, C=Consulta, B=Bloqueo, M=Mensaje Genérico,...',
  `texto` TEXT NULL COMMENT 'Texto con el mensaje de aviso.',
  
  `destino_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario relacionado, destinatario del aviso, o CERO si es para administración y aún no está aceptado/gestionado.',
  `origen_usuario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Usuario relacionado, origen del aviso, o CERO si es del sistema o de un administrador sin identificar.',
  
  `tienda_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Tienda relacionada con el aviso, o CERO si no tiene que ver.',  
  `articulo_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Artículo relacionado con el aviso o CERO si no tiene que ver.',
  `comentario_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Comentario relacionado con el aviso o NULL si no tiene que ver.',
  
  `fecha_lectura` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de lectura del aviso o NULL si no se ha leido o se ha desmarcado como tal.',
  `fecha_aceptado` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de aceptación del aviso o NULL si no se ha aceptado para su gestión por un moderador o administrador. No se usa en otros usuarios.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`moderadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`moderadores` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`moderadores` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  -- Usuario relacionado --
  `usuario_id` INT(12) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Usuario relacionado con estos datos principales, creado para acceder a la aplicación y al que hace referencia, o CERO (como si fuera NULL) si aún no existe porque se está creando y no se ha relacionado.',
  
  -- INI: Entidad(Empresa o Persona) --
  `nif_cif` VARCHAR(12) NOT NULL COMMENT 'Identificador de la entidad.',
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre si la entidad es de tipo persona.',
  `apellidos` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Apellidos si la entidad es de tipo persona.',
  `razon_social` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Razon social de la entidad si es de tipo empresa, o NULL si con el \"nombre y apellidos\" como persona es suficiente.',
  `direccion` TEXT NULL DEFAULT NULL COMMENT 'Direccion de la entidad o NULL si no quiere informar o no se conoce.',
  `region_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Región de localización de la entidad o CERO si no lo quiere informar (como si fuera NULL), aunque es recomendable.',
  `telefono_contacto` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Telefono de contacto directo con la entidad o NULL si no se sabe o no hay.',
  -- FIN: Entidad --
  
  -- Regiones-Moderador -- Se relacionan en tabla aparte.
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`regiones_moderador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`regiones_moderador` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`regiones_moderador` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `moderador_id` INT(12) UNSIGNED NOT NULL COMMENT 'Moderador relacionado con una Región para su moderación.',
  `region_id` INT(12) UNSIGNED NOT NULL COMMENT 'Región relacionada con el Moderador para que pueda gestionarla.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`usuarios` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `email` VARCHAR(255) NOT NULL COMMENT 'Correo Electronico y \"login\" principal del usuario. Debe ser único.',
  `password` VARCHAR(60) NOT NULL,
  `nick` VARCHAR(25) NOT NULL COMMENT 'Identificador del usuario y posible \"login\" secundario. Debe ser único.',
  
  -- INI: Entidad_Persona_Abreviada --
  `nombre` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nombre de la persona.',
  `apellidos` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Apellidos de la persona.',
  `direccion` TEXT NULL DEFAULT NULL COMMENT 'Direccion de la persona o NULL si no quiere informar o no se conoce.',
  `region_id` INT(12) UNSIGNED NULL DEFAULT '0' COMMENT 'Región de localización de la persona o CERO si no lo quiere informar (como si fuera NULL), aunque es recomendable, y necesario para comentar.',
  `telefono_contacto` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Telefono de contacto directo con la persona o NULL si no lo quiere informar, no se sabe o no hay.',
  `fecha_nacimiento` DATE NULL DEFAULT NULL COMMENT 'Fecha de nacimiento de la persona o NULL si no lo quiere informar.',
  -- FIN: Entidad_Persona_Abreviada --
  
  `fecha_registro` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora de registro del usuario o NULL si no se conoce por algún motivo (que no debería ser así).',
  `confirmado` TINYINT(1) NOT NULL COMMENT 'Indicador de que el usuario ha confirmado su registro o no.',
  
  `fecha_acceso` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora del ultimo acceso del usuario. Debería estar a NULL si no ha accedido nunca.',
  `num_accesos` INT(9) NOT NULL DEFAULT '0' COMMENT 'Contador de accesos fallidos del usuario o CERO si no ha tenido o se ha reiniciado por un acceso valido o por un administrador.',
  
  `bloqueado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indicador de usuario bloqueado: 0=No, 1=Si(bloqueado por accesos), 2=Si(bloqueado por administrador), ...',
  `fecha_bloqueo` DATETIME NULL DEFAULT NULL COMMENT 'Fecha y Hora del bloqueo del usuario. Debería estar a NULL si no está bloqueado o si se desbloquea.',
  `notas_bloqueo` TEXT NULL DEFAULT NULL COMMENT 'Notas visibles sobre el motivo del bloqueo del usuario o NULL si no hay -se muestra por defecto según indique \"bloqueado\"-.',
  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`configuraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`configuraciones` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`configuraciones` (
  `clave` VARCHAR(50) NOT NULL,
  `valor` TEXT NULL DEFAULT NULL,
  
  PRIMARY KEY (`clave`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`registros_aplicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw2_20_comparaprecios`.`registros_aplicacion` ;

CREATE TABLE IF NOT EXISTS `daw2_20_comparaprecios`.`registros_aplicacion` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  
  `fecha_registro` DATETIME NOT NULL COMMENT 'Fecha y Hora del registro de acceso.',
  `clase_log` CHAR(1) NOT NULL DEFAULT 'M' COMMENT 'Código de clase de log (fijado desde programación): E=Error(error), A=Aviso(warning), S=Seguimiento(trace), I=Información(info), D=Depuración(debug), ...',
  `modulo` VARCHAR(50) NULL DEFAULT 'app' COMMENT 'Modulo o Sección de la aplicación que ha generado el mensaje de registro.',
  `texto` TEXT NULL DEFAULT NULL COMMENT 'Texto con el mensaje de registro.',
  `ip` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Dirección IP desde donde accede el usuario (vale para IPv4 e IPv6.',
  `browser` TEXT NULL DEFAULT NULL COMMENT 'Texto con información del navegador utilizado en el acceso.',
  
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`procesos_aplicacion`
-- -----------------------------------------------------
-- Si se quieren gestionar los procesos desde la base de datos en lugar de
-- dejarlos fijos de forma programada, se debe definir alguna tabla para ello.

-- -----------------------------------------------------
-- Table `daw2_20_comparaprecios`.`copias_aplicacion`
-- -----------------------------------------------------
-- Si se quieren gestionar las copias de seguridad desde la base de datos sin
-- tener un sistema dinámico programado, que detecte las copias automáticamente
-- en el sistema de ficheros, se debe definir alguna tabla para ello.

-- -----------------------------------------------------
-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
